# install system package

dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update -y
  - sudo apt-get install linux-image-extra-$(uname -r) -y
  - sudo apt-get install linux-image-extra-virtual -y
  - sudo apt-get update -y
  - sudo apt-get install apt-transport-https -y
  - sudo apt-get install ca-certificates -y
  - sudo apt-get install curl -y
  - sudo apt-get install software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable"
  - sudo apt-get update -y
  - sudo apt-get install docker-ce -y
  - sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo usermod -aG docker $USER
  - sudo apt-get install postgresql-client

before_script:
  - docker run hello-world
  - docker-compose --version

# command to install dependencies
install:
  - git clone https://github.com/Nameles-Org/Nameles.git

script:
  - sudo docker-compose -f test-build-compose.yml up  --force-recreate --abort-on-container-exit
  - bash -c "[[ $(wc -l </tmp/db_counts.csv) -ge 1 ]] && head /tmp/db_counts.csv"
